spring:
    application:
        name: news-search-databatchimport
    data:
        elasticsearch:
            name: elasticsearch
            ip: 60.205.226.102
            port: 9300
            pool: 5

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    rabbitmq:
      host: ${RABBIT_MQ_HOST:59.110.241.166}
      port:  ${RABBIT_MQ_PORT:5672}
      username: superrd
      password: superrd
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1

server:
    port: 8709 #启动端口

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
          defaultZone: http://47.94.8.143:8761/eureka/

jwt:
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45

auth:
  serviceId: news-auth
  user:
      token-header: Authorization
  client:
      token-header: client-token
      id: news-search  #不填则默认读取spring.application.name
      secret: 123456