spring:
    application:
        name: news-center
server:
    port: 8761 #启动端口

eureka:
    instance:
      prefer-ip-address: true
      ip-address: 47.94.8.143
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
        service-url:
          defaultZone: http://47.94.8.143:8761/eureka/


